### ISSUE TITLE
Fix released weight asset filenames and broken pb file

### ISSUE THREAD

**Issue by daniel-j-h** [moabitcoin/ig65m-pytorch#12]
@sandhawalia looks like one of the onnx pb files are broken:

![gh](https://user-images.githubusercontent.com/527241/66118042-bb056b00-e5d5-11e9-9f5c-8e3311f2f5f3.png)

and the filenames do not match the syntax for torch hub:

https://github.com/pytorch/pytorch/blob/v1.2.0/torch/hub.py#L53-L54

Tasks
- [ ] re-upload broken pb file
- [ ] change release file name hash suffixes from `.._ig65m_0aa0550b.pth` to `_ig65m-0aa0550b.pth` (last delimiter has to be `-`)
- [ ] adapt urls in readme

**Comment by sandhawalia** [comment]
That model already exists right under the broken file. This file needs to be deleted

**Comment by sandhawalia** [comment]
I’ll have a look at the delimiter issue

**Comment by daniel-j-h** [comment]
Broken file deleted; file names updated. All done here!
