### ISSUE TITLE
Script to convert caffe to pytorch

### ISSUE THREAD

**Issue by sanchit2843** [moabitcoin/ig65m-pytorch#32]
Can you share any tool by which we can convert Caffe model to pytorch? Or if you can provide the same features for Ip-csn model.

**Comment by daniel-j-h** [comment]
The [convert tool](https://github.com/moabitcoin/ig65m-pytorch/blob/fc749e2ee354c3e4ddbb144cf511bb868b008f61/ig65m/cli/convert.py) converts weights from the provided pkl files to pytorch compatible format. The architecture is decoupled from the weights and is implemented [here](https://github.com/moabitcoin/ig65m-pytorch/blob/fc749e2ee354c3e4ddbb144cf511bb868b008f61/ig65m/models.py).

We don't support the CSN models right now - see https://github.com/moabitcoin/ig65m-pytorch/issues/9. If you want a pytorch version of them you'd have to implement the weight conversion and model definition (see links above).

**Comment by sanchit2843** [comment]
Thanks a lot.
