### ISSUE TITLE
using R(2+1)D features extraction instead of C3D

### ISSUE THREAD

**Issue by arash9900** [moabitcoin/ig65m-pytorch#33]
I am a newbie in machine learning and working on the implementation of [this paper] (https://github.com/WaqasSultani/AnomalyDetectionCVPR2018), it uses C3D for the feature extraction phase of its abnormal detection network and I am trying to use R(2+1)D instead of C3D. 
Can you please tell me about the overall steps of replacing?

Thanks so much

**Comment by daniel-j-h** [comment]
Here is how to use the pre-trained models from Pytorch
- https://github.com/moabitcoin/ig65m-pytorch#pytorch-models

And here's an extract tool to extract the video features with the pre-trained models
- https://github.com/moabitcoin/ig65m-pytorch#tools

**Comment by arash9900** [comment]
thanks, Is there any way to batch extract video features?

**Comment by daniel-j-h** [comment]
The [extract tool](https://github.com/moabitcoin/ig65m-pytorch/blob/fc749e2ee354c3e4ddbb144cf511bb868b008f61/ig65m/cli/extract.py) works one video at a time and runs batches of multiple clips through the model already.

**Comment by daniel-j-h** [comment]
Closing here; everything is in place for you to get started! :hugs:
