### ISSUE TITLE
Something wrong when run code : torch.hub.list("moabitcoin/ig65m-pytorch")

### ISSUE THREAD

**Issue by huamgmin** [moabitcoin/ig65m-pytorch#36]
hi, l'm a new hand in pytorch and when l run the code : torch.hub.list("moabitcoin/ig65m-pytorch")
I got Run error: IncompleteRead: IncompleteRead(0 bytes read)
Then I have try run code :   import http.client
                                           http.client.HTTPConnection._http_vsn = 1
                                           http.client.HTTPConnection._http_vsn_str = 'HTTP/1.0'
                                          torch.hub.list("moabitcoin/ig65m-pytorch")
but I got another run error:   BadZipFile: File is not a zip file
Can someone help me solve this problem！
THANKS

**Comment by daniel-j-h** [comment]
Works for me in a fresh Ubuntu container with Python3 and latest torch and torchvision.

https://github.com/moabitcoin/ig65m-pytorch#pytorch-models

What's your operating system, python, torch, and torchvision version?

**Comment by huamgmin** [comment]
operating system：Win10 ; python3.7.6 ;  torch 1.4+cpu ; torchvision 0.5+cpu. 
SO you  suspect  it's a problem about  version?  I'll try yours, hope it can work.

**Comment by daniel-j-h** [comment]
Any updates here?

**Comment by huamgmin** [comment]
Oh,sorry l forget it. I have run the code on ubuntu and  follow the advice you gave , it does work now. Thank you !!
