### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by Farabi-shafkat** [moabitcoin/ig65m-pytorch#40]
I was wondering how i should  cite  this work in a paper. I have  used pretrained weights provided by this repository in my work

**Comment by daniel-j-h** [comment]
Please cite the original 

https://github.com/facebookresearch/vmz

and related work the folks have done

https://github.com/moabitcoin/ig65m-pytorch#references-book

all we provide are ported weights for pytorch. The weights are 1:1 ported.

If you still want to cite this pytorch port, then see

https://raw.githubusercontent.com/moabitcoin/ig65m-pytorch/master/AUTHORS.md

Would be awesome if you could share a link to your your work/paper once it's openly accessible 😊

**Comment by Farabi-shafkat** [comment]
Thank you for the response. I really appreciate it. And yes i will definitely share it as soon as i have an openly accessible version.

**Comment by Farabi-shafkat** [comment]
Hello. 

I reopened the issue to share a pre-print of our work uploaded on arxiv. I have used the weights provided in this repository to perform some of the experiments described in our work.

https://arxiv.org/abs/2102.10555?fbclid=IwAR1qLsuEcjilSAl4qsDvPnMwwuXzcz2mYvcCSBVS6U7WRs48LjKDCeVtZns

Thanks for providing the weights

Regards, 
Farabi
